name: Workflow CI/CD Slim PHP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Staging
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Sync files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: metrobalim.service.mosframtech.com
          username: ${{ secrets.STAGING_USER }}
          password: ${{ secrets.STAGING_PASSWORD }}
          local-dir: ./ # Perbaikan: Tambahkan . untuk local-dir
          server-dir: ./
          exclude: |
            .git/**
            .git**
            .git*/**
            **/.git*
            **/.git*/**
            .github/**
            README.md
            .env.example
            /lost+found
            vendor/** # Menambahkan Vendor ke exclude